name: monthly_expense_flutter_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  # csv: ^6.0.0
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.1.2
  share_plus: ^10.0.0
  image_picker: ^1.0.4
  shared_preferences: ^2.5.4

  flutter_riverpod: ^2.5.1

  # Backend
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # Utilities
  intl: ^0.19.0 # Reverted to standard, override handles the rest
  uuid: ^4.3.3
  google_fonts: ^6.1.0
    # Add this line
  flutter_launcher_icons: ^0.13.1

  # Rich Text Editor
  flutter_quill: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ----------------------------------------------------------
# ADD THIS SECTION TO FIX THE VERSION CONFLICT
# ----------------------------------------------------------
dependency_overrides:
  intl: ^0.20.0

flutter:
  uses-material-design: true

# Add this configuration section at the bottom of the file
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # optional
  # adaptive_icon_background: "#FFFFFF" # Enable this if you have a background color preference
  # adaptive_icon_foreground: "assets/icon/app_icon.png" # For Android adaptive icons